services:
  - name: web-app
    type: web
    repo: https://github.com/Ohenheim/ESGI.Render.4A.Static
    env: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: API_KEY
        value: your-api-key
